import { theme } from '../styles/theme';

export const styles = {
  container: {
    padding: '2rem',
    width: '100%',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
    backgroundColor: theme.colors.background.primary,
    minHeight: '100vh',
  },
  section: {
    backgroundColor: theme.colors.background.secondary,
    borderRadius: '12px',
    padding: '2rem',
    boxShadow: theme.shadows.md,
    border: `1px solid ${theme.colors.border.primary}`,
  },
  sectionTitle: {
    fontSize: '1.75rem',
    fontWeight: '600',
    color: '#FFFFFF', // updated to white
    marginBottom: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  form: {
    width: '100%',
    marginBottom: '1.5rem',
  },
  inputContainer: {
    display: 'flex',
    gap: '1rem',
    position: 'relative',
  },
  input: {
    flex: 1,
    padding: '1rem 1.25rem',
    fontSize: '1rem',
    border: `2px solid ${theme.colors.border.secondary}`,
    borderRadius: '8px',
    outline: 'none',
    transition: 'all 0.2s',
    backgroundColor: theme.colors.background.tertiary,
    color: theme.colors.text.primary,
    '&:focus': {
      borderColor: theme.colors.accent.primary,
      boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.1)',
    },
  },
  button: {
    padding: '0.75rem 1.5rem',
    backgroundColor: theme.colors.accent.primary,
    color: theme.colors.text.primary,
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    '&:hover': {
      backgroundColor: theme.colors.accent.primary,
      transform: 'translateY(-1px)',
    },
  },
  responseContainer: {
    marginTop: '2rem',
    padding: '1.5rem',
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: '8px',
    border: `1px solid ${theme.colors.border.secondary}`,
  },
  responseTitle: {
    fontSize: '1.1rem',
    fontWeight: '600',
    color: '#FFFFFF', // updated to white
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  response: {
    color: theme.colors.text.secondary,
    lineHeight: '1.7',
  },
  error: {
    padding: '1rem',
    backgroundColor: theme.colors.background.tertiary,
    borderRadius: '8px',
    border: `1px solid ${theme.colors.accent.error}`,
    color: theme.colors.accent.error,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  aiIcon: {
    color: theme.colors.accent.primary,
  },
  warningIcon: {
    color: theme.colors.accent.error,
  },
  loadingSpinner: {
    width: '20px',
    height: '20px',
    border: `3px solid ${theme.colors.text.primary}`,
    borderTop: `3px solid ${theme.colors.background.tertiary}`,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
};