export const styles = {
  container: {
    padding: "32px",
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: "#f8fafc",
    minHeight: "100vh",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  headerTitle: {
    fontSize: "28px",
    fontWeight: "600",
    color: "#1e293b",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  viewToggle: {
    marginBottom: "24px",
    display: "flex",
    gap: "12px",
    background: "#fff",
    padding: "6px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    width: "fit-content",
  },
  radioLabel: {
    fontSize: "14px",
    cursor: "pointer",
    color: "#64748b",
    padding: "8px 16px",
    borderRadius: "6px",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#f1f5f9",
    },
    "&.active": {
      backgroundColor: "#0ea5e9",
      color: "#fff",
    },
  },
  sortIntervalContainer: {
    display: "flex",
    gap: "16px",
    marginBottom: "24px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  sortLabel: {
    fontSize: "14px",
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  select: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    color: "#334155",
    backgroundColor: "#fff",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      borderColor: "#94a3b8",
    },
    "&:focus": {
      outline: "none",
      borderColor: "#0ea5e9",
      boxShadow: "0 0 0 2px rgba(14,165,233,0.2)",
    },
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0",
    backgroundColor: "#fff",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  tableHeaderRow: {
    backgroundColor: "#f8fafc",
  },
  tableHeader: {
    padding: "16px",
    fontSize: "12px",
    fontWeight: "600",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    textAlign: "left",
    borderBottom: "1px solid #e2e8f0",
  },
  tableRow: {
    transition: "background-color 0.2s ease",
    "&:hover": {
      backgroundColor: "#f8fafc",
    },
  },
  tableCell: {
    padding: "16px",
    fontSize: "14px",
    color: "#334155",
    borderBottom: "1px solid #e2e8f0",
  },
  linkCell: {
    cursor: "pointer",
    color: "#0ea5e9",
    padding: "16px",
    fontWeight: "500",
    transition: "color 0.2s ease",
    "&:hover": {
      color: "#0284c7",
    },
  },
  chartCell: {
    width: "150px",
    padding: "12px 16px",
  },
  sparklineContainer: {
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    transition: "background-color 0.2s ease",
    "&:hover": {
      backgroundColor: "#f1f5f9",
    },
  },
  chartButton: {
    padding: "8px 12px",
    backgroundColor: "#0ea5e9",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#0284c7",
    },
  },
  removeButton: {
    padding: "8px 12px",
    backgroundColor: "#fff",
    color: "#ef4444",
    border: "1px solid #ef4444",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#ef4444",
      color: "#fff",
    },
  },
  optionChartContainer: {
    marginTop: "24px",
    padding: "24px",
    backgroundColor: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)",
  },
  priceUp: {
    color: "#10b981",
    fontWeight: "500",
  },
  priceDown: {
    color: "#ef4444",
    fontWeight: "500",
  },
  noData: {
    textAlign: "center",
    padding: "48px 24px",
    color: "#64748b",
    fontSize: "16px",
  },
  toggleButton: {
    padding: "10px 20px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  errorMessage: {
    padding: "20px",
    textAlign: "center",
    color: "#ef4444",
    fontSize: "14px",
    backgroundColor: "#fee2e2",
    borderRadius: "6px",
    margin: "20px 0",
  },
};