"""add_watchlist_id_to_option_premium_history

Revision ID: 52ee37a9714f
Revises: 
Create Date: 2025-05-23 23:01:59.937781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ee37a9714f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_premium_history', sa.Column('watchlist_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_option_premium_history_watchlist_id'), 'option_premium_history', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_premium_history_watchlist_id'), table_name='option_premium_history')
    op.drop_column('option_premium_history', 'watchlist_id')
    # ### end Alembic commands ###
